language: node_js

sudo: false

node_js:
  - '4'

addons:
  apt_packages:
    - graphicsmagick

notifications:
  email:
    smcarthur@mozilla.com
    jrgm@mozilla.com
  irc:
    channels:
      - 'irc.mozilla.org#fxa-bots'
    use_notice: false
    skip_join: false

env:
  - NODE_ENV=test DB=memory IMG=local
  - NODE_ENV=test DB=mysql IMG=local
  - NODE_ENV=test DB=mysql IMG=aws

before_install:
  - npm config set spin false
  - "mysql -e 'DROP DATABASE IF EXISTS fxa_profile;'"
  - "mysql -e 'CREATE DATABASE fxa_profile;'"

script:
  - npm run outdated
  - grunt nsp --force # check for vulnerable modules via nodesecurity.io
  - grunt
